server:
  port: 8082

spring:
  application.name: module-api
  datasource:
    url: jdbc:mysql://localhost:3306/kakao_talk
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: kakao_talk
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info
