server:
  port: 8080

spring:
  application.name: module-websocket
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: kakao_talk
    redis:
      host: localhost
      port: 6379